#!/bin/bash

# Preamble so bootscripts will find us
if [ "$1" == "--type" ]; then
  echo Upgrade
  exit 0
fi

CBCDRIVE=$2
PRINT='/psp/rfs1/fb_print'

BOOT=/mnt/kiss-usb
KISS=/mnt/kiss
USER=/mnt/user
USB=/mnt/usb

BOOT_DEV=/dev/${CBCDRIVE}1
KISS_DEV=/dev/${CBCDRIVE}2
USER_DEV=/dev/${CBCDRIVE}3

CBCLUA_TGZ=$USB/cbclua.tgz
CBCLUA_DIR=$USER/code/cbclua

echo "CBCLua Installer v0.1" | $PRINT
echo "By Matthew Thompson" | $PRINT

# This makes it so vista won't want to error check the drive
echo "Remounting usb drive read-only" | $PRINT
mount -r -o remount $USB -v 2>&1 | $PRINT

if [ ! -f $CBCLUA_TGZ ]; then
	echo "Error: This thumbdrive does not contain cbclua.tgz." | $PRINT
	echo "Please place this file on the thumbdrive" | $PRINT
	echo "and try again." | $PRINT
	exit 1
fi

echo "Installing in 5 seconds.." | $PRINT

sleep 5

echo "Mounting boot partition read-only" | $PRINT
mkdir $BOOT 2>&1 | $PRINT
mount $BOOT_DEV $BOOT -t vfat -v -o ro 2>&1 | $PRINT

echo "Loading ext2.ko" | $PRINT
insmod $BOOT/ext2.ko 2>&1 | $PRINT

echo "Mounting user parition read-write" | $PRINT
mkdir $USER 2>&1 | $PRINT
mount $USER_DEV $USER -t ext2 -v -o rw 2>&1 | $PRINT

echo "Extracting files to user partition" | $PRINT
rm -rf $USER/code/cbclua 2>&1 | $PRINT
tar -xzfp $CBCLUA_TGZ -C $USER/code 2>&1 | $PRINT

echo "Unmounting partitions" | $PRINT
umount $BOOT -v 2>&1 | $PRINT
umount $USER -v 2>&1 | $PRINT

echo "" | $PRINT

echo "Finished! Reboot and enjoy!" | $PRINT
echo "To uninstall CBCLua, simply delete it" | $PRINT
echo "on the program screen." | $PRINT
echo "If CBCLua seems to cause any problems" | $PRINT
echo "simply re-install a firmware userhook0" | $PRINT
