# This is what a makefile for a C module should look like!

# modpath place the module in this directory(s) relative to lua. 
# For example, lua will call this module cbclua.rawio
# You might want to put your schools letters as the modpath to avoid conflicts
modpath:=cbclua

# modname is the name of the module. All C module names must be themselves be unique 
# for the build system to work correctly. (even if in different modpaths)
modname:=rawio

# This line must be included in the Makefile. Otherwise it won't do anything
include ../../../shared.mk
